### ISSUE TITLE
[Request] 1.12.2 support

### ISSUE THREAD

**Issue by Fogapod** [lehjr/ModularPowerArmor#14]
README.md says that 1.7 support has ended, but nothing about 1.12. The majority of mods is still on this version.

**Comment by Fogapod** [comment]
https://github.com/MachineMuse/MachineMusePowersuits/issues/956#issuecomment-590515593 Just found this comment, please update README.md

**Comment by Fogapod** [comment]
There are actually two 1.12 branches, but no releases on GitHub/CurseForge, are these available somewhere?

**Comment by lehjr** [comment]
The code for MPS 1.12.2 is here: https://github.com/MachineMuse/MachineMusePowersuits/tree/1.12.2-experimental
